name: cobaya-tutorials
channels:
  - conda-forge
dependencies:
  - python=3.11
  - setuptools >= 80.0.0
  - numpy
  - matplotlib
  - pandas
  - scipy
  - pip:
    - camb
    - classy
    - cobaya
    - getdist
